### ISSUE TITLE
Implementing the Blue-Green Deployment Strategy on k8s

### ISSUE THREAD

**Issue by duythien** [duythien/rust-qa#1]
blue-deployment.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
spec:
  replicas: 3
  selector:
    matchLabels:
      version: blue
  template:
    metadata:
      labels:
        version: blue
    spec:
      containers:
      - image: nginx:1.23.0
        name: nginx
        ports:
        - containerPort: 80
``` 

```
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

Check to ensure that the Pods can be reached using a curl command from a temporary Pod. Use the Service's DNS name to reach the Pods controlled by the existing Deployment.

$ kubectl run tmp --image=alpine/curl:3.14 --restart=Never -it --rm -- curl -sI nginx.default.svc.cluster.local | grep Server
Server: nginx/1.23.0

The returned headers will include the nginx server version.

## Creating a Green Deployment
Create a second Deployment named nginx-green with 3 replicas.

The Pod template of the Deployment should use container image nginx:1.23.4 and assign the label version=green
Create a second Deployment in the file green-deployment.yaml. Make sure to change the labels and the container image tag. The manifest is shown below:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
      version: green
  template:
    metadata:
      labels:
        version: green
    spec:
      containers:
      - image: nginx:1.23.4
        name: nginx
        ports:
        - containerPort: 80
```
Create the Deployment object using the following command:

$ kubectl apply -f green-deployment.yaml
deployment.apps/nginx-green created

Wait until all replicas transition into the "Running" status.

$ kubectl get pods -l version=green
NAME                           READY   STATUS    RESTARTS   AGE
nginx-green-658cfdc9c6-8pvpp   1/1     Running   0          11s
nginx-green-658cfdc9c6-fdgm6   1/1     Running   0          11s
nginx-green-658cfdc9c6-zg6gl   1/1     Running   0          11s

## Switching to the Green Deployment
Change the Service's label selection so that traffic will be routed to the Pods controlled by the Deployment nginx-green.

Delete the Deployment named nginx-blue.

Run a temporary Pod with the container image alpine/curl:3.14 to make a call against the Service.

Change the existing service.yaml file by changing the label value with the key version from blue to green:
```
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    version: green
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```
Apply the changes to the Service object:

$ kubectl apply -f service.yaml
service/nginx configured

Delete the initial Deployment using the following command:

$ kubectl delete deployment nginx-blue
deployment.apps "nginx-blue" deleted

Incoming traffic to the Service endpoint should now be switched over to the Pods controlled by the green Deployment.

$ kubectl run tmp --image=alpine/curl:3.14 --restart=Never -it --rm -- curl -sI nginx.default.svc.cluster.local | grep Server
Server: nginx/1.23.4
